In [ ]:
%autosave 0

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
np.random.seed()

In [12]:
rng = np.random.default_rng(seed = 42)
#default_rng 

How likely is it that you roll doubles when rolling two dice?


In [24]:

rolled=rng.choice([1,2,3,4,5,6],(36,2))
rolled

array([[6, 6],
       [1, 2],
       [5, 1],
       [6, 2],
       [6, 2],
       [3, 4],
       [1, 4],
       [4, 5],
       [6, 4],
       [3, 3],
       [3, 5],
       [2, 2],
       [3, 1],
       [1, 1],
       [5, 5],
       [5, 3],
       [5, 1],
       [6, 4],
       [6, 1],
       [3, 5],
       [3, 3],
       [1, 3],
       [2, 2],
       [5, 4],
       [4, 3],
       [6, 1],
       [3, 1],
       [3, 6],
       [3, 6],
       [3, 5],
       [3, 2],
       [5, 6],
       [2, 5],
       [2, 5],
       [5, 3],
       [5, 2]])

In [25]:
row = 36
proportion=((rolled[:,0] == rolled[:,1]).sum())/row
proportion

0.19444444444444445

If you flip 8 coins, what is the probability of getting exactly 3 heads? 

In [29]:
#0 is tail, 1 is head
flips = rng.choice([0,1], (1_000,8))
flips

array([[1, 1, 1, ..., 1, 0, 0],
       [0, 1, 1, ..., 1, 1, 0],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [0, 1, 0, ..., 0, 1, 0],
       [1, 1, 0, ..., 0, 1, 1],
       [0, 1, 1, ..., 0, 0, 1]])

In [30]:
flips_sum = flips.sum(axis=1)
flips_sum[:5]

array([6, 4, 8, 2, 5])

In [32]:
(flips_sum==3).sum()  #every time you flip 8 coins, you get 3 head


221

In [33]:

propo=((flips_sum==3).sum()/1000)
propo

0.221

In [34]:
#What is the probability of getting more than 3 heads?
more_than_three_heads=((flips_sum>3).sum())
more_than_three_heads

634

In [35]:
#What is the probability of getting more than 3 heads?
more_than_three_heads=((flips_sum>3).sum()/1000)
more_than_three_heads

0.634

There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the probability that the two billboards I drive past both have data science students on them?

In [37]:

# Generate distributions for web development and data science cohorts
wd_co = rng.normal(loc=3, scale=1, size=1000)
ds_co = rng.normal(loc=1, scale=1, size=1000)
# Calculate the probability of randomly selecting a data science student for each billboard
probability_ds_billboard1 = np.sum(ds_co >= 1) / len(ds_co)
probability_ds_billboard2 = np.sum(ds_co >= 1) / len(ds_co)

# Probability that both billboards have data science students
probability_both_ds_billboards = probability_ds_billboard1 * probability_ds_billboard2
probability_both_ds_billboards


0.2304



Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

Compare Heights

Men have an average height of 178 cm and standard deviation of 8cm.
Women have a mean of 170, sd = 6cm.
Since you have means and standard deviations, you can use np.random.normal to generate observations.
If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?
When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

How likely is it that 450 students all download anaconda without an issue?

There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

How likely is it that a food truck will show up sometime this week?

If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?