In [10]:
%autosave 0

Autosave disabled


In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
np.random.seed()

In [12]:
rng = np.random.default_rng(seed = 42)
#default_rng 

How likely is it that you roll doubles when rolling two dice?


In [25]:

rolled=rng.choice([1,2,3,4,5,6],(36,2))
rolled[:5]

array([[4, 3],
       [1, 2],
       [6, 3],
       [1, 5],
       [5, 1]])

In [14]:
row = 36
proportion=((rolled[:,0] == rolled[:,1]).sum())/row
proportion

0.1388888888888889

If you flip 8 coins, what is the probability of getting exactly 3 heads? 

In [15]:
#0 is tail, 1 is head
flips = rng.choice([0,1], (1_000,8))
flips

array([[0, 0, 1, ..., 0, 1, 1],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 1, 0, ..., 0, 1, 0],
       ...,
       [1, 1, 0, ..., 1, 1, 1],
       [1, 0, 1, ..., 1, 0, 0],
       [1, 1, 0, ..., 0, 0, 0]])

In [16]:
flips_sum = flips.sum(axis=1)
flips_sum[:5]

array([3, 4, 5, 4, 6])

In [17]:
(flips_sum==3).sum()  #every time you flip 8 coins, you get 3 head


214

In [18]:

propo=((flips_sum==3).sum()/1000)
propo

0.214

In [19]:
#What is the probability of getting more than 3 heads?
more_than_three_heads=((flips_sum>3).sum())
more_than_three_heads

622

In [20]:

more_than_three_heads=((flips_sum>3).sum()/1000)
more_than_three_heads

0.622

There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the probability that the two billboards I drive past both have data science students on them?

In [21]:

# Generate distributions for web development and data science cohorts
wd_co = rng.normal(loc=3, scale=1, size=1000)
ds_co = rng.normal(loc=1, scale=1, size=1000)
# Calculate the probability of randomly selecting a data science student for each billboard
probability_ds_billboard1 = np.sum(ds_co >= 1) / len(ds_co)
probability_ds_billboard2 = np.sum(ds_co >= 1) / len(ds_co)

# Probability that both billboards have data science students
probability_both_ds_billboards = probability_ds_billboard1 * probability_ds_billboard2
probability_both_ds_billboards


0.28302400000000005

Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [ ]:

mean_poptarts_per_day = 3
std_dev_poptarts_per_day = 1.5
restocked_poptarts_on_monday = 17

# Calculate the mean and standard deviation for 5 days
mean_poptarts_5_days = mean_poptarts_per_day * 5
std_dev_poptarts_5_days = std_dev_poptarts_per_day * np.sqrt(5)

# Calculate the probability of being able to buy some poptarts on Friday afternoon
probability_buy_poptarts_friday = 1 - np.random.normal(loc=mean_poptarts_5_days, scale=std_dev_poptarts_5_days).cdf(restocked_poptarts_on_monday)

print(f"The likelihood of being able to buy some poptarts on Friday afternoon is approximately {probability_buy_poptarts_friday:.2%}")


Compare Heights

Men have an average height of 178 cm and standard deviation of 8cm.
Women have a mean of 170, sd = 6cm.
Since you have means and standard deviations, you can use np.random.normal to generate observations.
If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [22]:
# Given data
mean_height_men = 178
std_dev_men = 8
mean_height_women = 170
std_dev_women = 6

# Generate random observations for heights of men and women
heights_men = np.random.normal(loc=mean_height_men, scale=std_dev_men, size=100000)
heights_women = np.random.normal(loc=mean_height_women, scale=std_dev_women, size=100000)

# Calculate the probability that a woman is taller than a man
probability_woman_taller = np.mean(heights_women > heights_men)

print(f"The likelihood that a woman is taller than a man is approximately {probability_woman_taller:.2%}")


The likelihood that a woman is taller than a man is approximately 21.22%



What is the probability that we observe an installation issue within the first 150 students that download anaconda?

n=150

How likely is it that 450 students all download anaconda without an issue?






There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

array([[0.19584913, 0.5830939 , 0.73174074, ..., 0.6109273 , 0.57265114,
        0.8765419 ],
       [0.51684397, 0.80814468, 0.83759312, ..., 0.44996212, 0.75246845,
        0.87444671],
       [0.54113154, 0.82812348, 0.62820609, ..., 0.13688043, 0.76611939,
        0.74786739],
       ...,
       [0.48337291, 0.83585508, 0.13482723, ..., 0.92956135, 0.03390944,
        0.42855636],
       [0.22272309, 0.53687883, 0.65569468, ..., 0.56553088, 0.28488713,
        0.15274867],
       [0.62207147, 0.97344635, 0.33502206, ..., 0.91058887, 0.53474437,
        0.71206136]])

How likely is it that a food truck will show up sometime this week?

If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?